function data = SD1data

prompts = { 'Subject number',...
                    'Age',...
                    'Gender (f/m)',...
                    'Handedness (r/l)',...
                    };
datainput = inputdlg(prompts,'Experiment 1',1);
data(1).Nr = datainput{1};
data.age = datainput{2};
data.gender = datainput{3};
data.hand = datainput{4};
