function stimuluscommand = SD1stimulus(settings,trial)

% initialize
id = SD1columns;

stimuluscommand = ''; %preallocate
DisableKeysForKbCheck('empty'); % enable all keys

% make shorter
OW = settings.screen.ow;
OD = settings.screen.owd;
COL = settings.layout.colors;

% get layout
symbol = trial(id.syml);
if settings.training == 1
    color = settings.layout.redcolor;
else
    color = COL(trial(id.symc),:);
end
pos = trial(id.qdrn);

% get position (nw, ne, se, sw, l, r, center): [horizontal vertical] 
possiblepositions = [...
    OD(3)*1/3 OD(4)*1/3; ... % nw
    OD(3)*2/3 OD(4)*1/3; ... % ne
    OD(3)*2/3 OD(4)*2/3; ... % se
    OD(3)*1/3 OD(4)*2/3; ... % sw
    OD(3)*1/3 OD(4)*1/2; ... % l
    OD(3)*2/3 OD(4)*1/2; ... % r
    OD(3)*1/2 OD(4)*1/2; ... % center
    ];
screenposition = possiblepositions(pos,:);

% make stimulus
polygonstring = '';
if symbol == 0 % training: white vertical line
    polygonlayout = [...
        -1*settings.LU -2*settings.LU;...
        +1*settings.LU -2*settings.LU;...
        +1*settings.LU +2*settings.LU;...
        -1*settings.LU +2*settings.LU;...
        ];
    polygonposition(:,1) = polygonlayout(:,1) + screenposition(1);
    polygonposition(:,2) = polygonlayout(:,2) + screenposition(2);
    for is = 1:size(polygonposition,1)
        polygonstring = [polygonstring num2str(polygonposition(is,:)) '; '];
    end
    stimuluscommand = [stimuluscommand 'Screen(' char(39) 'FillPoly' char(39) ',' num2str(OW) ', [' num2str(settings.layout.redcolor) '] , [' polygonstring ']); '];      
elseif symbol == 1 % upward triangle
    polygonlayout = [...
        (-2-sqrt(2)/2)*settings.LU +2*settings.LU;...
        +0*settings.LU -2*settings.LU;...
        (+2+sqrt(2)/2)*settings.LU +2*settings.LU;...
        ];
    polygonposition(:,1) = polygonlayout(:,1) + screenposition(1);
    polygonposition(:,2) = polygonlayout(:,2) + screenposition(2);
    for is = 1:size(polygonposition,1)
        polygonstring = [polygonstring num2str(polygonposition(is,:)) '; '];
    end
    stimuluscommand = [stimuluscommand 'Screen(' char(39) 'FillPoly' char(39) ',' num2str(OW) ',[' num2str(color) '], [' polygonstring ']); '];
elseif symbol == 2 % downward triangle
    polygonlayout = [...
        (-2-sqrt(2)/2)*settings.LU -2*settings.LU;...
        +0*settings.LU +2*settings.LU;...
        (+2+sqrt(2)/2)*settings.LU -2*settings.LU;...
        ];
    polygonposition(:,1) = polygonlayout(:,1) + screenposition(1);
    polygonposition(:,2) = polygonlayout(:,2) + screenposition(2);
    for is = 1:size(polygonposition,1)
        polygonstring = [polygonstring num2str(polygonposition(is,:)) '; '];
    end
    stimuluscommand = [stimuluscommand 'Screen(' char(39) 'FillPoly' char(39) ',' num2str(OW) ',[' num2str(color) '], [' polygonstring ']); '];
elseif symbol == 3 % square
    polygonlayout = [...
        -2*settings.LU -2*settings.LU;...
        +2*settings.LU -2*settings.LU;...
        +2*settings.LU +2*settings.LU;...
        -2*settings.LU +2*settings.LU;...
        ];
    polygonposition(:,1) = polygonlayout(:,1) + screenposition(1);
    polygonposition(:,2) = polygonlayout(:,2) + screenposition(2);
    for is = 1:size(polygonposition,1)
        polygonstring = [polygonstring num2str(polygonposition(is,:)) '; '];
    end
    stimuluscommand = [stimuluscommand 'Screen(' char(39) 'FillPoly' char(39) ',' num2str(OW) ',[' num2str(color) '], [' polygonstring ']); '];    
elseif symbol == 4 % diamond
    polygonlayout = [...
        +0*settings.LU -2*settings.LU;...
        +2*settings.LU +0*settings.LU;...
        +0*settings.LU +2*settings.LU;...
        -2*settings.LU +0*settings.LU;...
        ]*sqrt(2);
    polygonposition(:,1) = polygonlayout(:,1) + screenposition(1);
    polygonposition(:,2) = polygonlayout(:,2) + screenposition(2);
    for is = 1:size(polygonposition,1)
        polygonstring = [polygonstring num2str(polygonposition(is,:)) '; '];
    end
    stimuluscommand = [stimuluscommand 'Screen(' char(39) 'FillPoly' char(39) ',' num2str(OW) ',[' num2str(color) '], [' polygonstring ']); '];      
elseif symbol == 5 % cross    
    polygonlayout = [...
        -1*settings.LU -2*settings.LU;...
        +1*settings.LU -2*settings.LU;...
        +1*settings.LU -1*settings.LU;...
        +2*settings.LU -1*settings.LU;...
        +2*settings.LU +1*settings.LU;...
        +1*settings.LU +1*settings.LU;...
        +1*settings.LU +2*settings.LU;...
        -1*settings.LU +2*settings.LU;...
        -1*settings.LU +1*settings.LU;...
        -2*settings.LU +1*settings.LU;...
        -2*settings.LU -1*settings.LU;...
        -1*settings.LU -1*settings.LU;...
        ];
    polygonposition(:,1) = polygonlayout(:,1) + screenposition(1);
    polygonposition(:,2) = polygonlayout(:,2) + screenposition(2);
    for is = 1:size(polygonposition,1)
        polygonstring = [polygonstring num2str(polygonposition(is,:)) '; '];
    end
    stimuluscommand = [stimuluscommand 'Screen(' char(39) 'FillPoly' char(39) ',' num2str(OW) ',[' num2str(color) '], [' polygonstring ']); '];      
elseif symbol == 6 % hexagon
    polygonlayout = [...
        -1*settings.LU -2*settings.LU;...
        +1*settings.LU -2*settings.LU;...
        +2*settings.LU -0*settings.LU;...
        +1*settings.LU +2*settings.LU;...
        -1*settings.LU +2*settings.LU;...
        -2*settings.LU +0*settings.LU;...
        ];
    polygonposition(:,1) = polygonlayout(:,1) + screenposition(1);
    polygonposition(:,2) = polygonlayout(:,2) + screenposition(2);
    for is = 1:size(polygonposition,1)
        polygonstring = [polygonstring num2str(polygonposition(is,:)) '; '];
    end
    stimuluscommand = [stimuluscommand 'Screen(' char(39) 'FillPoly' char(39) ',' num2str(OW) ',[' num2str(color) '], [' polygonstring ']); '];      

elseif symbol == 7 % two horiztonal lines, one vertical
    polygonlayout = [...
        -2*settings.LU -2*settings.LU;...
        +2*settings.LU -2*settings.LU;...
        +2*settings.LU -1*settings.LU;...
        +.5*settings.LU -1*settings.LU;...
        +.5*settings.LU +1*settings.LU;...
        +2*settings.LU +1*settings.LU;...
        +2*settings.LU +2*settings.LU;...
        -2*settings.LU +2*settings.LU;...
        -2*settings.LU +1*settings.LU;...
        -.5*settings.LU +1*settings.LU;...
        -.5*settings.LU -1*settings.LU;...
        -2*settings.LU -1*settings.LU;...
        ];
    polygonposition(:,1) = polygonlayout(:,1) + screenposition(1);
    polygonposition(:,2) = polygonlayout(:,2) + screenposition(2);
    for is = 1:size(polygonposition,1)
        polygonstring = [polygonstring num2str(polygonposition(is,:)) '; '];
    end
    stimuluscommand = [stimuluscommand 'Screen(' char(39) 'FillPoly' char(39) ',' num2str(OW) ',[' num2str(color) '], [' polygonstring ']); '];      
elseif symbol == 8 % circile
    stimuluscommand = [stimuluscommand 'Screen(' char(39) 'DrawDots' char(39) ',' num2str(OW) ',[' num2str(screenposition) '], ' num2str(64) ', [' num2str(color) '],[0 0], 1); '];
end
